# Generated by Django 5.2.8 on 2026-01-09 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_doctorprofile_is_booking_open_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='work_days',
            field=models.JSONField(blank=True, help_text='Робочі дні тижня: 0=Пн … 6=Нд', null=True),
        ),
    ]
