# Generated by Django 5.2.8 on 2025-12-29 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chatmessage_delete_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['created_at']},
        ),
    ]
