# Generated by Django 5.2.8 on 2025-12-12 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField(help_text='Дата та час початку консультації.')),
                ('duration_minutes', models.PositiveIntegerField(default=30, help_text='Тривалість прийому в хвилинах (за замовчуванням 30 хв).')),
                ('status', models.CharField(choices=[('pending', 'Очікує підтвердження'), ('confirmed', 'Підтверджено'), ('completed', 'Завершено'), ('canceled', 'Скасовано')], default='pending', help_text='Поточний статус запису.', max_length=20)),
                ('reason', models.TextField(blank=True, help_text='Причина звернення, короткий опис симптомів тощо.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата й час створення запису.')),
                ('updated_at', models.DateTimeField(auto_now_add=True, help_text='Дата й час останнього оновлення запису.')),
                ('doctor', models.ForeignKey(help_text='Профіль лікаря, до якого записуються.', on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='accounts.doctorprofile')),
                ('patient', models.ForeignKey(help_text='Профіль пацієнта, який записався на прийом.', on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='accounts.patientprofile')),
            ],
            options={
                'ordering': ['-start_datetime'],
                'unique_together': {('patient', 'doctor', 'start_datetime')},
            },
        ),
    ]
