# Generated by Django 5.2.8 on 2025-12-17 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_alter_appointment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Очікує підтвердження'), ('confirmed', 'Підтверджено'), ('completed', 'Завершено')], default='pending', help_text='Поточний статус запису.', max_length=20),
        ),
    ]
