# Generated by Django 5.2.8 on 2025-12-12 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_type', models.CharField(blank=True, max_length=3)),
                ('allergies', models.TextField(blank=True)),
                ('chronic_diseases', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.OneToOneField(help_text='Пацієнт, якому належить ця медична картка.', on_delete=django.db.models.deletion.CASCADE, related_name='medical_card', to='accounts.patientprofile')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.CharField(help_text='Основний діагноз або попередній діагноз.', max_length=255)),
                ('recipe', models.TextField(blank=True, help_text='Рецепти', null=True)),
                ('recommendations', models.TextField(blank=True, help_text='Рекомендації щодо лікування', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата створення')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Дата оновлення')),
                ('appointment', models.ForeignKey(blank=True, help_text="Пов'язаний запис прийому (необов'язково).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_records', to='appointments.appointment')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='medical.medicalcard')),
                ('doctor', models.ForeignKey(help_text='Лікар, який зробив цей запис.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_records', to='accounts.doctorprofile')),
            ],
        ),
    ]
