# Generated by Django 5.2.8 on 2025-12-11 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('issued_date', models.DateField()),
                ('valid_until', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='InsurancePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance_policy', models.CharField(max_length=50, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('provider', models.CharField(max_length=255)),
                ('valid_until', models.DateField()),
            ],
        ),
    ]
